name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**/values.yaml'

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: node-app
  
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Lint Test
        working-directory: ./app
        run: npm i -g eslint && npm run lint

      - name: Build Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

      - name: Tag Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
      
      # - name: Push Docker Image
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REGISTRY
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      #     echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Update image tag in Helm package values.yaml
        run: |
          sed -i "s/tag:.*/tag: $IMAGE_TAG/g" helm/node-app/values.yaml

          # Check that the tag has been updated
          if [[ $(cat helm/node-app/values.yaml | grep "$IMAGE_TAG") == "$IMAGE_TAG" ]]; then
            echo "Tag updated successfully"
          else
            echo "Tag update failed"
            exit 1
          fi

      - name: Push values changes to repo without actions trigger
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add helm/node-app/values.yaml
          git commit -m "Update values.yaml with new image tag"
          git push origin main
